server:
  port: ${PORT}

spring:
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  
logging:
  level:
    org.springframework.r2dbc: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

rapidapi:
  key: ${RAPIDAPI_APIKEY}
  colorize:
    url: ${RAPIDAPI_COLORIZE_URL}
    host: ${RAPIDAPI_COLORIZE_HOST}
  remove-bg:
    url: ${RAPIDAPI_REMOVEBG_URL}
    host: ${RAPIDAPI_REMOVEBG_HOST}