# kubectl apply -f jesus-sanchez-36-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: jesus-sanchez-36-secret
  namespace: jesus-sanchez-36-namespace
type: Opaque
data:
  PORT: ODA4NQ==  
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLWZyYWdyYW50LXdpbmQtYTRiNXo1NDgtcG9vbGVyLnVzLWVhc3QtMS5hd3MubmVvbi50ZWNoL25lb25kYj9zc2xNb2RlPVJFUVVJUkU=  
  DATABASE_USERNAME: bmVvbmRiX293bmVy  
  DATABASE_PASSWORD: bnBnXzRSQVRiSkRLVTFTdg==   
  RAPIDAPI_COLORIZE_URL: aHR0cHM6Ly9jb2xvcml6ZS1waG90bzEucC5yYXBpZGFwaS5jb20vY29sb3JpemVfaW1hZ2Vfd2l0aF9hdXRvX3Byb21wdA==   
  RAPIDAPI_COLORIZE_HOST: Y29sb3JpemUtcGhvdG8xLnAucmFwaWRhcGkuY29t 
  RAPIDAPI_REMOVEBG_URL: aHR0cHM6Ly9haS1iYWNrZ3JvdW5kLXJlbW92ZXIucC5yYXBpZGFwaS5jb20vaW1hZ2UvbWF0dGUvdjE=   
  RAPIDAPI_REMOVEBG_HOST: YWktYmFja2dyb3VuZC1yZW1vdmVyLnAucmFwaWRhcGkuY29t  
  RAPIDAPI_APIKEY: YTc3OGM1MDhkNW1zaDIwZGJlYThhNjI4Yzc1YnAxMzY0MWFqc25iNTc2NDdhNzE3YTA=   

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode