name: Render Deploy

on:
  workflow_run:
    workflows: ["Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
          echo "Deploy triggered on Render"